### ISSUE TITLE
`near-lib` is pointing to the archived dependency

### ISSUE THREAD

**Issue by djsatok** [near/rainbow-token-connector#23]
At the moment `bridge-token-factory` is using `near-lib`:
``` rust
near-lib = { git = "https://github.com/ilblackdragon/balancer-near", rev = "a386305c9829d2e5302a78fdc475c8a279fcf6ed"}
```
The dependency is outdated, @ilblackdragon moved the code [here](https://github.com/ilblackdragon/contracts/tree/master/near-lib-rs/src). We need to update the dependency.

**Comment by mfornet** [comment]
Moreover, in the README of the [new repository](https://github.com/ilblackdragon/contracts) you can read: 

```
All contracts are not code reviewed, come as is, have no guarantees.
```

We should code-review and pin a particular commit, since token-connector is a security critical application.

Another option is to add reference vanilla implementation of Fungible Token to `core-contracts` where only sound and maintained contracts are kept as suggested in https://github.com/near/near-sdk-rs/pull/289#issuecomment-777458586

**Comment by ilblackdragon** [comment]
The code for this library is moving to near-sdk-rs in this PR: https://github.com/near/near-sdk-rs/pull/275

This PR was blocked on fixing simulation. There might be some other blockers there, I'm not sure.
Plus the FT standard will get upgraded to 141 from 21, which means this repo should also upgrade with that change.

**Comment by djsatok** [comment]
@mikedotexe, please take a look at near/near-sdk-rs#275 This should be the place for reference implementation of NEP-141!

**Comment by mfornet** [comment]
This will be fixed by removing this dependency when https://github.com/near/rainbow-token-connector/issues/21 is implemented.
